markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
gravatar: 123
url: http://chamerling.github.com/QuickHubApp
feedburner: quickhubapp
ga: UA-26468797-1
disqus: quickhubapp
twitter: chamerling
title: QuickHub.App
subtitle: Access to GitHub from your OS X Status bar
author: Christophe Hamerling
